version: '3'
services:
  php-server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "php:8.3-apache"
    container_name: "${APP_NAME}-server"
    volumes:
      - ./:/var/www/html/
      - './docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
      - './docker/apache/mpm_prefork.conf:/etc/apache2/mods-enabled/mpm_prefork.conf'
    ports:
      - "${SERVER_PORT}:80"
    environment:
      - PHP_REDIS_SESSIONS=${REDIS_SESSIONS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - APP_NAME=${APP_NAME}
    depends_on:
      - redis
      - db
  redis:
    image: redis:latest
    container_name: "${APP_NAME}-redis"
    ports:
      - "${REDIS_PORT}:6379"
  db:
    image: mariadb:latest
    container_name: "${APP_NAME}-db"
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
      - ./docker/db/settings/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${APP_NAME}-phpmyadmin"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db